package mocks

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i route256/checkout/internal/domain/services.ProductManager -o ./mocks\product_manager_mock.go -n ProductManagerMock

import (
	"context"
	"route256/checkout/internal/domain"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ProductManagerMock implements services.ProductManager
type ProductManagerMock struct {
	t minimock.Tester

	funcGetProduct          func(ctx context.Context, sku uint32) (pp1 *domain.Product, err error)
	inspectFuncGetProduct   func(ctx context.Context, sku uint32)
	afterGetProductCounter  uint64
	beforeGetProductCounter uint64
	GetProductMock          mProductManagerMockGetProduct
}

// NewProductManagerMock returns a mock for services.ProductManager
func NewProductManagerMock(t minimock.Tester) *ProductManagerMock {
	m := &ProductManagerMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetProductMock = mProductManagerMockGetProduct{mock: m}
	m.GetProductMock.callArgs = []*ProductManagerMockGetProductParams{}

	return m
}

type mProductManagerMockGetProduct struct {
	mock               *ProductManagerMock
	defaultExpectation *ProductManagerMockGetProductExpectation
	expectations       []*ProductManagerMockGetProductExpectation

	callArgs []*ProductManagerMockGetProductParams
	mutex    sync.RWMutex
}

// ProductManagerMockGetProductExpectation specifies expectation struct of the ProductManager.GetProduct
type ProductManagerMockGetProductExpectation struct {
	mock    *ProductManagerMock
	params  *ProductManagerMockGetProductParams
	results *ProductManagerMockGetProductResults
	Counter uint64
}

// ProductManagerMockGetProductParams contains parameters of the ProductManager.GetProduct
type ProductManagerMockGetProductParams struct {
	ctx context.Context
	sku uint32
}

// ProductManagerMockGetProductResults contains results of the ProductManager.GetProduct
type ProductManagerMockGetProductResults struct {
	pp1 *domain.Product
	err error
}

// Expect sets up expected params for ProductManager.GetProduct
func (mmGetProduct *mProductManagerMockGetProduct) Expect(ctx context.Context, sku uint32) *mProductManagerMockGetProduct {
	if mmGetProduct.mock.funcGetProduct != nil {
		mmGetProduct.mock.t.Fatalf("ProductManagerMock.GetProduct mock is already set by Set")
	}

	if mmGetProduct.defaultExpectation == nil {
		mmGetProduct.defaultExpectation = &ProductManagerMockGetProductExpectation{}
	}

	mmGetProduct.defaultExpectation.params = &ProductManagerMockGetProductParams{ctx, sku}
	for _, e := range mmGetProduct.expectations {
		if minimock.Equal(e.params, mmGetProduct.defaultExpectation.params) {
			mmGetProduct.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetProduct.defaultExpectation.params)
		}
	}

	return mmGetProduct
}

// Inspect accepts an inspector function that has same arguments as the ProductManager.GetProduct
func (mmGetProduct *mProductManagerMockGetProduct) Inspect(f func(ctx context.Context, sku uint32)) *mProductManagerMockGetProduct {
	if mmGetProduct.mock.inspectFuncGetProduct != nil {
		mmGetProduct.mock.t.Fatalf("Inspect function is already set for ProductManagerMock.GetProduct")
	}

	mmGetProduct.mock.inspectFuncGetProduct = f

	return mmGetProduct
}

// Return sets up results that will be returned by ProductManager.GetProduct
func (mmGetProduct *mProductManagerMockGetProduct) Return(pp1 *domain.Product, err error) *ProductManagerMock {
	if mmGetProduct.mock.funcGetProduct != nil {
		mmGetProduct.mock.t.Fatalf("ProductManagerMock.GetProduct mock is already set by Set")
	}

	if mmGetProduct.defaultExpectation == nil {
		mmGetProduct.defaultExpectation = &ProductManagerMockGetProductExpectation{mock: mmGetProduct.mock}
	}
	mmGetProduct.defaultExpectation.results = &ProductManagerMockGetProductResults{pp1, err}
	return mmGetProduct.mock
}

// Set uses given function f to mock the ProductManager.GetProduct method
func (mmGetProduct *mProductManagerMockGetProduct) Set(f func(ctx context.Context, sku uint32) (pp1 *domain.Product, err error)) *ProductManagerMock {
	if mmGetProduct.defaultExpectation != nil {
		mmGetProduct.mock.t.Fatalf("Default expectation is already set for the ProductManager.GetProduct method")
	}

	if len(mmGetProduct.expectations) > 0 {
		mmGetProduct.mock.t.Fatalf("Some expectations are already set for the ProductManager.GetProduct method")
	}

	mmGetProduct.mock.funcGetProduct = f
	return mmGetProduct.mock
}

// When sets expectation for the ProductManager.GetProduct which will trigger the result defined by the following
// Then helper
func (mmGetProduct *mProductManagerMockGetProduct) When(ctx context.Context, sku uint32) *ProductManagerMockGetProductExpectation {
	if mmGetProduct.mock.funcGetProduct != nil {
		mmGetProduct.mock.t.Fatalf("ProductManagerMock.GetProduct mock is already set by Set")
	}

	expectation := &ProductManagerMockGetProductExpectation{
		mock:   mmGetProduct.mock,
		params: &ProductManagerMockGetProductParams{ctx, sku},
	}
	mmGetProduct.expectations = append(mmGetProduct.expectations, expectation)
	return expectation
}

// Then sets up ProductManager.GetProduct return parameters for the expectation previously defined by the When method
func (e *ProductManagerMockGetProductExpectation) Then(pp1 *domain.Product, err error) *ProductManagerMock {
	e.results = &ProductManagerMockGetProductResults{pp1, err}
	return e.mock
}

// GetProduct implements services.ProductManager
func (mmGetProduct *ProductManagerMock) GetProduct(ctx context.Context, sku uint32) (pp1 *domain.Product, err error) {
	mm_atomic.AddUint64(&mmGetProduct.beforeGetProductCounter, 1)
	defer mm_atomic.AddUint64(&mmGetProduct.afterGetProductCounter, 1)

	if mmGetProduct.inspectFuncGetProduct != nil {
		mmGetProduct.inspectFuncGetProduct(ctx, sku)
	}

	mm_params := &ProductManagerMockGetProductParams{ctx, sku}

	// Record call args
	mmGetProduct.GetProductMock.mutex.Lock()
	mmGetProduct.GetProductMock.callArgs = append(mmGetProduct.GetProductMock.callArgs, mm_params)
	mmGetProduct.GetProductMock.mutex.Unlock()

	for _, e := range mmGetProduct.GetProductMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.pp1, e.results.err
		}
	}

	if mmGetProduct.GetProductMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetProduct.GetProductMock.defaultExpectation.Counter, 1)
		mm_want := mmGetProduct.GetProductMock.defaultExpectation.params
		mm_got := ProductManagerMockGetProductParams{ctx, sku}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetProduct.t.Errorf("ProductManagerMock.GetProduct got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetProduct.GetProductMock.defaultExpectation.results
		if mm_results == nil {
			mmGetProduct.t.Fatal("No results are set for the ProductManagerMock.GetProduct")
		}
		return (*mm_results).pp1, (*mm_results).err
	}
	if mmGetProduct.funcGetProduct != nil {
		return mmGetProduct.funcGetProduct(ctx, sku)
	}
	mmGetProduct.t.Fatalf("Unexpected call to ProductManagerMock.GetProduct. %v %v", ctx, sku)
	return
}

// GetProductAfterCounter returns a count of finished ProductManagerMock.GetProduct invocations
func (mmGetProduct *ProductManagerMock) GetProductAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetProduct.afterGetProductCounter)
}

// GetProductBeforeCounter returns a count of ProductManagerMock.GetProduct invocations
func (mmGetProduct *ProductManagerMock) GetProductBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetProduct.beforeGetProductCounter)
}

// Calls returns a list of arguments used in each call to ProductManagerMock.GetProduct.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetProduct *mProductManagerMockGetProduct) Calls() []*ProductManagerMockGetProductParams {
	mmGetProduct.mutex.RLock()

	argCopy := make([]*ProductManagerMockGetProductParams, len(mmGetProduct.callArgs))
	copy(argCopy, mmGetProduct.callArgs)

	mmGetProduct.mutex.RUnlock()

	return argCopy
}

// MinimockGetProductDone returns true if the count of the GetProduct invocations corresponds
// the number of defined expectations
func (m *ProductManagerMock) MinimockGetProductDone() bool {
	for _, e := range m.GetProductMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetProductMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetProductCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetProduct != nil && mm_atomic.LoadUint64(&m.afterGetProductCounter) < 1 {
		return false
	}
	return true
}

// MinimockGetProductInspect logs each unmet expectation
func (m *ProductManagerMock) MinimockGetProductInspect() {
	for _, e := range m.GetProductMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ProductManagerMock.GetProduct with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetProductMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetProductCounter) < 1 {
		if m.GetProductMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to ProductManagerMock.GetProduct")
		} else {
			m.t.Errorf("Expected call to ProductManagerMock.GetProduct with params: %#v", *m.GetProductMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetProduct != nil && mm_atomic.LoadUint64(&m.afterGetProductCounter) < 1 {
		m.t.Error("Expected call to ProductManagerMock.GetProduct")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ProductManagerMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockGetProductInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ProductManagerMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ProductManagerMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetProductDone()
}
